### ISSUE TITLE
【友链添加请求】添加KHLFYY's Blog

### ISSUE THREAD

**Issue by KHLFYY** [CoderLiuChina/coderliuchina.github.io#1]
名称：KHLFYY's Blog
作者：KHLFYY
头像：https://pic.imgdb.cn/item/610faeba5132923bf88a2bde.png
网址：https://www.khlfyy.top

另：请参考[我博客内](https://www.khlfyy.top)VGTB友链并添加

**Comment by KHLFYY** [comment]
由于众所周知的原因，托管在github page的www.khlfyy.top可能不太好访问
可以访问 https://cloudflare.khlfyy.top/ 代替

**Comment by CoderLiuChina** [comment]
加好了！

**Comment by KHLFYY** [comment]
等过一个月我有时间的时候把你的加上（ 最近没啥时间

**Comment by KHLFYY** [comment]
才想起来 这就加上（
